/// Non-comprehensive list of element attributes.
public enum ElementAttribute: String {
    // Informational attributes.
    case role = "AXRole"
    case subrole = "AXSubrole"
    case roleDescription = "AXRoleDescription"
    case title = "AXTitle"
    case description = "AXDescription"
    case help = "AXHelp"

    // Hierarchical relationship attributes.
    case parentElement = "AXParent"
    case childElements = "AXChildren"
    case childElementsInNavigationOrder = "AXChildrenInNavigationOrder"
    case selectedChildrenElements = "AXSelectedChildren"
    case visibleChildrenElements = "AXVisibleChildren"
    case windowElement = "AXWindow"
    case topLevelElement = "AXTopLevelUIElement"
    case titleElement = "AXTitleUIElement"
    case servesAsTitleForElement = "AXServesAsTitleForUIElement"
    case linkedElements = "AXLinkedUIElements"
    case sharedFocusElements = "AXSharedFocusElements"
    case focusableAncestor = "AXFocusableAncestor"

    // Visual state attributes.
    case isEnabled = "AXEnabled"
    case isFocused = "AXFocused"
    case position = "AXPosition"
    case size = "AXSize"

    // Value attributes.
    case value = "AXValue"
    case valueDescription = "AXValueDescription"
    case minValue = "AXMinValue"
    case maxValue = "AXMaxValue"
    case valueIncrement = "AXValueIncrement"
    case valueWraps = "AXValueWraps"
    case allowedValues = "AXAllowedValues"
    case placeholderValue = "AXPlaceholderValue"

    // Text-specific attributes.
    case selectedText = "AXSelectedText"
    case selectedTextRange = "AXSelectedTextRange"
    case selectedTextRanges = "AXSelectedTextRanges"
    case visibleTextRange = "AXVisibleTextRange"
    case numberOfCharacters = "AXNumberOfCharacters"
    case sharedTextElements = "AXSharedTextUIElements"
    case sharedCharacteRange = "AXSharedCharacterRange"
    case insertionPointLineNumber = "AXInsertionPointLineNumber"

    // Top-level element attributes.
    case isMain = "AXMain"
    case isMinimized = "AXMinimized"
    case closeButton = "AXCloseButton"
    case zoomButton = "AXZoomButton"
    case minimizeButton = "AXMinimizeButton"
    case toolbar = "AXToolbarButton"
    case fullScreenButton = "AXFullScreenButton"
    case proxy = "AXProxy"
    case growArea = "AXGrowArea"
    case isModal = "AXModal"
    case defaultButton = "AXDefaultButton"
    case cancelButton = "AXCancelButton"

    // Menu-specific attributes.
    case menuItemCmdChar = "AXMenuItemCmdChar"
    case menuItemCmdVirtualKey = "AXMenuItemCmdVirtualKey"
    case menuItemCmdGlyph = "AXMenuItemCmdGlyph"
    case menuItemCmdModifiers = "AXMenuItemCmdModifiers"
    case menuItemMarkChar = "AXMenuItemMarkChar"
    case menuItemPrimaryElement = "AXMenuItemPrimaryUIElement"

    // Attributes specific to application elements.
    case menuBar = "AXMenuBar"
    case windows = "AXWindows"
    case frontmostWindow = "AXFrontmost"
    case hidden = "AXHidden"
    case mainWindow = "AXMainWindow"
    case focusedWindow = "AXFocusedWindow"
    case focusedElement = "AXFocusedUIElement"
    case extrasMenuBar = "AXExtrasMenuBar"

    // Table attributes.
    case rows = "AXRows"
    case visibleRows = "AXVisibleRows"
    case selectedRows = "AXSelectedRows"
    case columns = "AXColumns"
    case visibleColumns = "AXVisibleColumns"
    case selectedColumns = "AXSelectedColumns"
    case selectedCells = "AXSelectedCells"
    case sortDirection = "AXSortDirection"
    case columnHeaderElements = "AXColumnHeaderUIElements"
    case index = "AXIndex"
    case disclosing = "AXDisclosing"
    case disclosedRows = "AXDisclosedRows"
    case disclosedByRow = "AXDisclosedByRow"

    // Role-specific attributes.
    case horizontalScrollBar = "AXHorizontalScrollBar"
    case verticalScrollBar = "AXVerticalScrollBar"
    case orientation = "AXOrientation"
    case header = "AXHeader"
    case edited = "AXEdited"
    case tabs = "AXTabs"
    case overflowButton = "AXOverflowButton"
    case fileName = "AXFilenameAttribute"
    case expanded = "AXExpanded"
    case selected = "AXSelected"
    case splitters = "AXSplitters"
    case contents = "AXContents"
    case nextContents = "AXNextContents"
    case previousContents = "AXPreviousContents"
    case document = "AXDocument"
    case incrementer = "AXIncrementer"
    case decrementButton = "AXDecrementButton"
    case incrementButton = "AXIncrementButton"
    case columnTitle = "AXColumnTitle"
    case url = "AXURL"
    case labelValue = "AXLabelValue"
    case shownMenuElement = "AXShownMenuUIElement"
    case focusedApplication = "AXFocusedApplication"
    case elementBusy = "AXElementBusy"
    case alternateUIVisible = "AXAlternateUIVisible"
    case isApplicationRunning = "AXIsApplicationRunning"
    case searchButton = "AXSearchButton"
    case clearButton = "AXClearButton"

    // Level indicator attributes.
    case warningValue = "AXWarningValue"
    case criticalValue = "AXCriticalValue"
}
